### ISSUE TITLE
Complete Authentication flow

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Quizzer#24]
## Overview 😄

This Project is being built on **MERN** stack, we are using *nodejs*, *passport.js*, *passport-local strategy* and *jwt* to build the authentication. 
In future we may add login with **google** or **github**. Backend API authentication is created, it was not tested, so I don't know about any error that might come up during connecting to the front end.

## TODO
- [x] Doumentation of backend API 
- [ ] Create Login and signup Pages in frontend 
- [ ] Create actions for loging and signing up 
- [ ] Complete Auth flow, with redirects and state updates
