### ISSUE TITLE
Create Complete Auth flow for backend

### ISSUE THREAD

**Issue by Souvikns** [Ninja-Developers/Quizzer#5]
## TODO
- [x] Passport setup for local and jwt
- [x] Create routes for login and signup 
- [x] Create user schema on mongoose, with appropriate middlewares
